config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'ajax#input'
  post 'ajax/result'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ajax_controller.rb
# frozen_string_literal: true

class AjaxController < ApplicationController
  before_action :parse_params, only: :result

  def input; end

  def result
    @result ||= string.split.sort_by(&:size).reverse.join(' ')
  end

  private

  attr_reader :string

  def parse_params
    @string = params[:string]
    @result = 'Вы ввели пустую строку.' if string && string.empty?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/ajax_helper.rb
# frozen_string_literal: true

module AjaxHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/ajax/input.html.erb
<h1>Сортировка слов в строке</h1>

<p>С клавиатуры вводится строка со словами, разделенными пробелами. Выведите новую строку, сформированную
из введенной путем перестановки местами слов в порядке убывания их длины.</p>

<div id="form">
  <%= form_with method: :post, url: ajax_result_url do |form| %>
    <%= form.text_field :string, placeholder: 'Введите строку', required: true %>
    <%= form.submit 'Отправить' %>
  <% end %>
</div>

<div id="result">
</div>

app/views/ajax/result.js.erb
document.querySelector('#result').innerText = '<%= escape_javascript @result %>';

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeleniumExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>